languageCode = "en-gb"
title = "Visual Artist and VJ"
baseurl = "http://www.alien-101.com/"
theme = "prologue"
publishDir = "html"

[params]
  name = "Alien 101"
  description = "Visual artist and VJ"
  copyright = "Alien 101"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/msoleramarquez"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:lola@alien-101.com?Subject=Enquiry"

# Portfolio column one

[[params.portfolio1]]
title = "Mannequin"
alt = "Mannequin"
source = "img/pic04.jpg"

[[params.portfolio1]]
  title = "Tokyo"
  alt = "Tokyo"
  source = "img/pic06.jpg"

# Portfolio column two

[[params.portfolio2]]
  title = "Pop Art"
  alt = "Pop Art"
  source = "img/pic03.jpg"

  [[params.portfolio2]]
    title = "Exist"
    alt = "Exist"
    source = "img/pic08.jpg"

# Portfolio column 3

[[params.portfolio3 ]]
title = "We Are Not Alone"
alt = "We Are Not Alone"
source = "img/pic07.jpg"

[[params.portfolio3]]
  title = "Alien"
  alt = "Alien"
  source = "img/pic05.jpg"
