languageCode = "en-gb"
title = "Visual Artist and VJ"
baseurl = "http://www.alien-101.com/"
theme = "prologue"
publishDir = "html"

[params]
  name = "Alien 101"
  description = "Visual artist and VJ"
  copyright = "Alien 101"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/_alien101"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/msoleramarquez"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:lola@alien-101.com?Subject=Enquiry"

# Portfolio column one

[[params.portfolio1]]
title = "Out of Space"
alt = "Out of Space"
  source = "img/pic09.png"

  [[params.portfolio1]]
    title = "Green Man"
    alt = "Green Man"
    source = "img/pic10.jpg"

    [[params.portfolio1]]
      title = "Astronauts"
      alt = "Astronauts"
      source = "img/pic06.jpg"

# Portfolio column two

[[params.portfolio2]]
  title = "Cosmic"
  alt = "Cosmic"
  source = "img/pic03.jpg"

  [[params.portfolio2]]
    title = "UFO Engineer"
    alt = "UFO Engineer"
    source = "img/pic01.jpg"

  [[params.portfolio2]]
    title = "Exist"
    alt = "Exist"
    source = "img/pic08.jpg"

# Portfolio column 3

  [[params.portfolio3]]
  title = "Doll Parts"
  alt = "Doll Parts"
    source = "img/pic05.png"

[[params.portfolio3]]
title = "Mannequin"
alt = "Mannequin"
source = "img/pic04.png"

[[params.portfolio3 ]]
title = "We Are Not Alone"
alt = "We Are Not Alone"
source = "img/pic07.jpg"
