languageCode = "en-gb"
title = "Visual Artist and VJ"
baseurl = "http://www.alien-101.com/"
theme = "prologue"
publishDir = "html"

# Minification and optimization settings
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = false
      precision = 2
    [minify.tdewolff.html]
      keepComments = false
      keepDefaultAttrVals = false
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 2

# Output formats for better caching
[caches]
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "24h"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "1h"
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "1h"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "24h"

[params]
  name = "Alien101"
  description = "Visuals for<br />electronic music"
  copyright = "Matt Gourd 2025"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/_alien101"

  [[params.social]]
    medium = "vimeo"
    icon = "vimeo"
    link = "https://vimeo.com/user2160487"


[[params.social]]
    medium = "facebook"
    icon = "facebook"
    link = "https://www.facebook.com/msoleramarquez"


# Portfolio column one

[[params.portfolio1]]
title = "Out of Space"
alt = "Out of Space"
  source = "https://res.cloudinary.com/diy2hv1ds/image/upload/v1587468093/pic09_lss8sr.jpg"

  [[params.portfolio1]]
    title = "Green Man"
    alt = "Green Man"
    source = "https://res.cloudinary.com/diy2hv1ds/image/upload/v1583321474/pic10_wnh3tm.png"

    [[params.portfolio1]]
      title = "Astronauts"
      alt = "Astronauts"
      source = "https://res.cloudinary.com/diy2hv1ds/image/upload/v1583321464/pic06_xibgnm.jpg"

# Portfolio column two

[[params.portfolio2]]
  title = "Cosmic"
  alt = "Cosmic"
  source = "https://res.cloudinary.com/diy2hv1ds/image/upload/v1587468119/pic03_gea4eh.png"

  [[params.portfolio2]]
    title = "UFO Engineer"
    alt = "UFO Engineer"
    source = "https://res.cloudinary.com/diy2hv1ds/image/upload/v1583321463/pic01_hcs0ix.jpg"

  [[params.portfolio2]]
    title = "Exist"
    alt = "Exist"
    source = "https://res.cloudinary.com/diy2hv1ds/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1583321465/pic08_fhuosh.jpg"

# Portfolio column 3

  [[params.portfolio3]]
  title = "Doll Parts"
  alt = "Doll Parts"
    source = "https://res.cloudinary.com/diy2hv1ds/image/upload/c_scale,w_326/v1583321475/pic05_pykhti.png"

[[params.portfolio3]]
title = "Mannequin"
alt = "Mannequin"
source = "https://res.cloudinary.com/diy2hv1ds/image/upload/v1583321470/pic04_ymw9io.png"

[[params.portfolio3 ]]
title = "We Are Not Alone"
alt = "We Are Not Alone"
source = "https://res.cloudinary.com/diy2hv1ds/image/upload/v1583321464/pic07_jkjgg8.jpg"
