languageCode = "en-gb"
title = "Visual Artist and VJ"
baseurl = "http://www.alien-101.com/"
theme = "prologue"

[params]
  name = "Alien 101"
  description = "Visual artist and VJ"
  copyright = "Alien 101"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/msoleramarquez"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:lola@alien-101.com?Subject=Enquiry"

# Portfolio column one

[[params.portfolio1]]
  title = "Spastik Abducted"
  alt = "Spastik Abducted"
  source = "img/pic01.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Aphex Twin Alien"
  alt = "Aphex Twin Alien"
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Marilyn"
  alt = "Marilyn"
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Escape Woman"
  alt = "Escape Woman"
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Kraftwerk"
  alt = "Kraftwerk"
  source = "img/pic05.jpg"
  url = "#"

  [[params.portfolio2]]
    title = "Exist"
    alt = "Exist"
    source = "img/pic08.jpg"
    url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Tokyo"
  alt = "Tokyo"
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "We Are Not Alone"
  alt = "We Are Not Alone"
  source = "img/pic07.jpg"
  url = "#"

  [[params.portfolio3]]
    title = "Stop Wars"
    alt = "Stop Wars"
    source = "img/pic09.jpg"
    url = "#"
